Workflow:
  '@WorkflowId': '{91e9be79-d00b-f111-8406-0022486402c1}'
  '@Name': 【工藤修正中】F05-008-住所マスタ突合
  JsonFileName: /modernflows/91e9be79-d00b-f111-8406-0022486402c1/F05-008--91E9BE79-D00B-F111-8406-0022486402C1.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.2.0.1
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1041
      '@description': 【工藤修正中】F05-008-住所マスタ突合
