Workflow:
  '@WorkflowId': '{35b37bd8-f4c5-f011-bbd3-000d3a330200}'
  '@Name': F-05-002_項目補正-AIプロンプト実行
  JsonFileName: /modernflows/35b37bd8-f4c5-f011-bbd3-000d3a330200/F-05-002_-AI-35B37BD8-F4C5-F011-BBD3-000D3A330200.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 0
  StatusCode: 1
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.1.0.36
  IsCustomizable: 1
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1041
      '@description': F-05-002_項目補正-AIプロンプト実行
