Workflow:
  '@WorkflowId': '{270e505f-d1c5-f011-bbd3-000d3a36c479}'
  '@Name': F-06-001_データインポート終了処理
  JsonFileName: /modernflows/270e505f-d1c5-f011-bbd3-000d3a36c479/F-06-001_-270E505F-D1C5-F011-BBD3-000D3A36C479.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.1.0.35
  IsCustomizable: 1
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1041
      '@description': F-06-001_データインポート終了処理
