Workflow:
  '@WorkflowId': '{fcd20e5a-13c5-f011-bbd2-000d3a4028ea}'
  '@Name': S-03-001_詳細データの取得
  '@Description': このフローは、入力パラメーターを必要とせずにトリガーされます。起動するとすぐに、成功を示すステータスコードを含む応答を送信します。応答には追加のデータやプロパティは含まれていません。基本的に、フローがトリガーされ正常に完了したことを確認するシンプルな確認メカニズムとして機能しますが、特定の情報を処理したり返したりすることはありません。
  JsonFileName: /modernflows/fcd20e5a-13c5-f011-bbd2-000d3a4028ea/S-03-001_-FCD20E5A-13C5-F011-BBD2-000D3A4028EA.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0
  IsCustomizable: 1
  RendererObjectTypeCode: 0
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 1
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1041
      '@description': S-03-001_詳細データの取得
  Descriptions:
    Description:
      '@languagecode': 1041
      '@description': このフローは、入力パラメーターを必要とせずにトリガーされます。起動するとすぐに、成功を示すステータスコードを含む応答を送信します。応答には追加のデータやプロパティは含まれていません。基本的に、フローがトリガーされ正常に完了したことを確認するシンプルな確認メカニズムとして機能しますが、特定の情報を処理したり返したりすることはありません。
