Workflow:
  '@WorkflowId': '{04709006-8cbf-f011-bbd2-000d3a403447}'
  '@Name': S-02-001_エラーリスト一覧の取得
  '@Description': このフローは入力パラメーターを必要とせずにトリガーされます。起動するとすぐに、成功を示すステータスコードと空のオブジェクトをレスポンスコンテンツとして送信します。フローは追加の処理やデータ操作を行いません。
  JsonFileName: /modernflows/04709006-8cbf-f011-bbd2-000d3a403447/S-02-001_-04709006-8CBF-F011-BBD2-000D3A403447.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0
  IsCustomizable: 1
  RendererObjectTypeCode: 0
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 1
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1041
      '@description': S-02-001_エラーリスト一覧の取得
  Descriptions:
    Description:
      '@languagecode': 1041
      '@description': このフローは入力パラメーターを必要とせずにトリガーされます。起動するとすぐに、成功を示すステータスコードと空のオブジェクトをレスポンスコンテンツとして送信します。フローは追加の処理やデータ操作を行いません。
