Workflow:
  '@WorkflowId': '{fdb05eeb-5506-f111-8406-00224862f0be}'
  '@Name': S-04-003_問い合わせ起票
  JsonFileName: /modernflows/fdb05eeb-5506-f111-8406-00224862f0be/S-04-003_-FDB05EEB-5506-F111-8406-00224862F0BE.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 1
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1041
      '@description': S-04-003_問い合わせ起票
